DEFAULT_MAX_PHYS_DIM = 50
DEFAULT_MAX_BOND_DIM = 500

DEFAULT_CUTOFF = 1e-15
DEFAULT_LORENTZIAN = 1e-15

BACKENDS = ('TORCH', 'TF', 'SCIPY')

DEFAULT_SVD_BACKEND = 'SCIPY'
DEFAULT_BACKPROP_BACKEND = 'SCIPY'


CANO_DECOMPS = ('SVD', 'QR')
DEFAULT_CANO_DECOMP = 'QR'

MPS_OPERATION_MODES = ('FAST', 'SLOW')
DEFAULT_MPS_OPERATION_MODE = 'FAST'
